### ISSUE TITLE
infocmp-Exception in IntelliJ-Terminal

### ISSUE THREAD

**Issue by MaaxGr** [kotlin-inquirer/kotlin-inquirer#4]
Hi,

if i execute this snippet in IntelliJ, i get the following error:

```
KInquirer.promptInput("Enter telephone number: ")
```

```
? Enter telephone number:  Feb 13, 2021 8:15:42 PM org.jline.utils.Log logr
WARNING: Unable to retrieve infocmp for type dumb-color
java.io.IOException: Cannot run program "infocmp": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.jline.utils.InfoCmp.getInfoCmp(InfoCmp.java:547)
	at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:187)
	at org.jline.terminal.impl.DumbTerminal.<init>(DumbTerminal.java:88)
	at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:401)
	at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:259)
	at com.yg.kotlin.inquirer.core.KInquirer.runTerminal(KInquirer.kt:25)
	at com.yg.kotlin.inquirer.core.KInquirer.prompt(KInquirer.kt:11)
	at com.yg.kotlin.inquirer.components.InputComponentKt.promptInput(InputComponent.kt:72)
	at com.yg.kotlin.inquirer.components.InputComponentKt.promptInput$default(InputComponent.kt:70)
	at com.maaxgr.telekram.cli.MainKt$main$1$telekram$1.invoke(Main.kt:18)
	at com.maaxgr.telekram.cli.MainKt$main$1$telekram$1.invoke(Main.kt)
	at com.maaxgr.telekram.lib.InternalTelekramApi.onAuthorizationStateUpdated(InternalTelekramApi.kt:124)
	at com.maaxgr.telekram.lib.InternalTelekramApi.access$onAuthorizationStateUpdated(InternalTelekramApi.kt:24)
	at com.maaxgr.telekram.lib.InternalTelekramApi$UpdateHandler.onResult(InternalTelekramApi.kt:349)
	at it.tdlight.common.InternalClient.handleResponse(InternalClient.java:87)
	at it.tdlight.common.InternalClient.handleEvent(InternalClient.java:102)
	at it.tdlight.common.InternalClient.handleEvents(InternalClient.java:63)
	at it.tdlight.common.InternalClientManager.handleClientEvents(InternalClientManager.java:38)
	at it.tdlight.common.ResponseReceiver.run(ResponseReceiver.java:90)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 20 more

```

Any idea or plan how to fix this?

**Comment by YanivGrama** [comment]
AFAIK, intellij terminal behaves differently
I didn't invest time to figure out how to act on keyboard key press
I'll check it out soon
thanks again for all of you feedback
